### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by toxoxi** [niemuuu/yapla#2]
- [x] [Research how to make it minimum feature #1 ](https://github.com/niemuuu/simple-youtube-player/issues/1)
- [x] Implement minimum feature
  - [x] play music with `videoId` prepared in advance
  - [x] search with some words and play these
- [ ] Improve
  - [ ] random play
  - [ ] interactive UI
  - [ ] check whether video-player (ex: mpv) has installed ([ref](https://github.com/mps-youtube/mps-youtube/blob/4279caa5f343aa6ad14a2d550d1c65d1d745f4dc/mps_youtube/util.py#L64-L84))
  - [ ] preload (ref: https://github.com/niemuuu/simple-youtube-player/issues/1#issuecomment-461999600)
